# Generated by Django 3.1.7 on 2021-03-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='skills_level_id',
            new_name='skill_level_id',
        ),
    ]
